services:
  - type: web
    name: hmart-ai-api
    runtime: python
    rootDir: backend/ai_microservice
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: sql103.infinityfree.com
      - key: DB_USER
        value: if0_42101441
      - key: DB_PASS
        value: Ujmz9BohZg
      - key: DB_NAME
        value: if0_42101441_db_ecommerce
    plan: free
