services:
  - type: web
    name: hmart-ai-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r ai_microservice/requirements.txt
    startCommand: uvicorn ai_microservice.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: buihalkspfwuvlu04ujx-mysql.services.clever-cloud.com
      - key: DB_USER
        value: umk0gm7jacsvmt8
      - key: DB_PASS
        value: 70FLmaThui6plsJdmxtD
      - key: DB_NAME
        value: buihalkspfwuvlu04ujx
    plan: free
